version: '2.2'
services:
    config-server:
        container_name: config-server
        build:
            context: .
            dockerfile: atech-config-server/Dockerfile-atechconfigserver
        image: openjdk:8u171-jdk-alpine3.8
        expose:
            - 8081
        ports:
            - 8081:8081
        networks:
            - emp-network        
    server-register:
        container_name: server-register
        environment:
                  SPRING_APPLICATION_JSON: '{"spring":{"application":{"name": "atech-server-register"},"cloud":{"config":{"uri":"http://config-server:8081"}}}}'
        build:
            context: .
            dockerfile: atech-server-register/Dockerfile-atechserverregister
        image: openjdk:8u171-jdk-alpine3.8
        expose:
            - 8082
        ports:
            - 8082:8082
        networks:
            - emp-network        
        depends_on:
            - config-server
        logging:
            driver: json-file
    auth-serverdb:        
        container_name: auth-serverdb
        environment:
                  POSTGRES_USER: atech
                  POSTGRES_PASSWORD: atech
                  POSTGRES_DB: authserverdb
        image: postgres:10.5-alpine
        expose:
            - 5442
        ports:
            - 5442:5432
        networks:
            - emp-network
        logging:
            driver: json-file
    flight-controldb:        
        container_name: flight-controldb
        environment:
                  POSTGRES_USER: atech
                  POSTGRES_PASSWORD: atech
                  POSTGRES_DB: flightcontroldb
        image: postgres:10.5-alpine
        expose:
            - 5432
        ports:
            - 5432:5432
        networks:
            - emp-network
        logging:
            driver: json-file              
    auth-server:
        container_name: auth-server
        environment:
                  SPRING_APPLICATION_JSON: '{"spring":{"application":{"name": "atech-auth-server"},"cloud":{"config":{"uri":"http://config-server:8081"}}}}'
                  SPRING_DATASOURCE_URL: jdbc:postgresql://auth-serverdb:5442/authserverdb
        build:
            context: .
            dockerfile: atech-server-register/Dockerfile-atechserverregister
        image: openjdk:8u171-jdk-alpine3.8
        expose:
            - 8083
        ports:
            - 8083:8083
        networks:
            - emp-network        
        depends_on:
            - config-server
            - server-register
            - auth-serverdb
        logging:
            driver: json-file
    flight-control:
        container_name: flight-control
        environment:
                  SPRING_APPLICATION_JSON: '{"spring":{"application":{"name": "atech-flight-control"},"cloud":{"config":{"uri":"http://config-server:8081"}}}}'
                  SPRING_DATASOURCE_URL: jdbc:postgresql://flight-controldb:5432/flightcontroldb
        build:
            context: .
            dockerfile: flight-control/Dockerfile-flightcontrol
        image: openjdk:8u171-jdk-alpine3.8
        expose:
            - 8080
        ports:
            - 8080:8080
        networks:
            - emp-network        
        depends_on:
            - config-server
            - server-register
            - flight-controldb
            - auth-server
        logging:
            driver: json-file   
networks:
    emp-network:
        driver: bridge
